project:
  type: website

website:
  title: "Sample Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: Week07_NormDist.qmd
        text: "In-Class Notes: Week 07"
  sidebar:
      style: "docked"
      search: true
      contents:
        - index.qmd
        - about.qmd
        - section: "Class Notes"
          contents:
            - Week07_NormDist.qmd

format:
  html:
    theme:
      - lux
      - brand
    css: styles.css
    toc: true



